### PR TITLE
Implemented the Detector method

### PR DESCRIPTION
**Pull request by dtworth**
I am basically using DCC++ as a hook to send block occupancy to JMRI from wifi detectors.  These detectors are ESP01's located in track-powered boxcars which scan for ESP8266-based Access Points and report the strongest signal.  Status is sent to an ESP32 which is then connected to JMRI.

I plan on sharing the code for the ESP01's once I clean that up, but I wanted to make sure that the hook that I have added would remain stable within your code.

I believe that others could use this hook to implement wifi block detectors using IR or current sensing.

You are more than welcome to improve the code or suggest improvements.

I also added setHostname, and its associated initializers, so the ESP32 would be recognized by name.  This is important for the ESP01's so the don't have to rely upon a fixed IP address.

I also slipped in a change to the check for pin number so I could use GPIO0 as an input.

### CODE REVIEW

**Review by atanisoft — DISMISSED** [review]
Some adjustments will need to be made before this can be merged. We should model the Detector classes similar to how S88 sensors are implemented.

This should also be an optional module similar to S88 is today.

I am confused on a couple lines and will comment on them separately.

**Comment by dtworth** [comment]
I piddled around with this implementation before the S88 code was added.  I'll take a look.

**Comment by atanisoft** [comment]
Sounds good. I will check more of it later this evening and post more comments if needed

**Comment by dtworth** [comment]
I have updated the files so the use of the detector methods are optional.

**Comment by atanisoft** [comment]
I am going to switch this to target the development branch before merge so that it can have some further refinement before release. One piece that would be great to have before merge is conversion to S88Sensor style approach but I can convert that if needed.

After having read this PR further I think naming this as Detector may be incorrect as it is more of a RemoteSensor instead. It does not need to be limited to just Detectors. Any sort of RemoteSensor can feed back to the base station for reporting to JMRI or otherwise.

**Comment by dtworth** [comment]
Sounds good.  Perhaps the "R" command would be more appropriate instead of the "D" command, if that is available.

You are welcome to convert to the S88 approach, as long as the Remote Sensors get reported in a way that is compatible with the current version of JMRI.  I do not want to mess with JMRI just yet.

**Comment by atanisoft** [comment]
Unfortunately "R" is already allocated to reading CVs on the programming track. One benefit of DCCppESP32 is that we are not limited to single characters for the command IDs. We can use "RS" for Remote Sensors.

I'll merge this to the development branch and start the updates to bring it inline with the S88 approach.

**Comment by atanisoft** [comment]
@dtworth This has been merged to the development branch and converted to use the basic Sensor object. Please pull the development branch and review as there are some additional changes included in https://github.com/atanisoft/DCCppESP32/commit/a9127d3abe9f03f12aefa94d3442f168ca66dba8

**Pull request merged**
